# =============================================================================
#  Bloc3 — AMS2_tableau_etats.py
#  Tableau d'export des états AMS2 — compatible architecture modulaire.
# =============================================================================

TABLEAU_ETATS = [
    {
        "state_id":        "game_closed",
        "label":           "Jeu fermé",
        "politique":       "exit",
        "game_state":      "GAME_EXITED (0) ou processus absent",
        "session_state":   "N/A",
        "race_state":      "N/A",
        "pit_mode":        "N/A",
        "notes":           "",
    },
    {
        "state_id":        "loading",
        "label":           "Chargement",
        "politique":       "stop",
        "game_state":      "Processus présent, shared memory $pcars2$ indisponible",
        "session_state":   "N/A",
        "race_state":      "N/A",
        "pit_mode":        "N/A",
        "notes":           "Ou GAME_INGAME_RESTARTING (5).",
    },
    {
        "state_id":        "menus",
        "label":           "Menus",
        "politique":       "stop",
        "game_state":      "GAME_FRONT_END (1) / GAME_FRONT_END_REPLAY (7)",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "*",
        "notes":           "",
    },
    {
        "state_id":        "replay",
        "label":           "Replay",
        "politique":       "stop",
        "game_state":      "GAME_INGAME_REPLAY (6)",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "*",
        "notes":           "",
    },
    {
        "state_id":        "paused",
        "label":           "Pause",
        "politique":       "hold",
        "game_state":      "GAME_INGAME_PAUSED (3)",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "*",
        "notes":           "",
    },
    {
        "state_id":        "setup_menu",
        "label":           "Menu ingame (temps qui s'écoule)",
        "politique":       "stop",
        "game_state":      "GAME_INGAME_INMENU_TIME_TICKING (4)",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "*",
        "notes":           "Menus pendant une session active (setup, options…).",
    },
    {
        "state_id":        "pre_race",
        "label":           "Grille / avant départ / tour de formation",
        "politique":       "stop",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "SESSION_RACE (5) + RACESTATE_NOT_STARTED (1)  /  SESSION_FORMATION_LAP (4)",
        "race_state":      "RACESTATE_NOT_STARTED",
        "pit_mode":        "*",
        "notes":           "",
    },
    {
        "state_id":        "race",
        "label":           "En course",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "SESSION_RACE (5)",
        "race_state":      "RACESTATE_RACING (2) ou autre ≠ NOT_STARTED",
        "pit_mode":        "PIT_MODE_NONE",
        "notes":           "",
    },
    {
        "state_id":        "qualifying",
        "label":           "Qualifications",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "SESSION_QUALIFY (3)",
        "race_state":      "*",
        "pit_mode":        "PIT_MODE_NONE",
        "notes":           "",
    },
    {
        "state_id":        "practice",
        "label":           "Essais / Test",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "SESSION_PRACTICE (1) / SESSION_TEST (2)",
        "race_state":      "*",
        "pit_mode":        "PIT_MODE_NONE",
        "notes":           "",
    },
    {
        "state_id":        "time_attack",
        "label":           "Time attack",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "SESSION_TIME_ATTACK (6)",
        "race_state":      "*",
        "pit_mode":        "PIT_MODE_NONE",
        "notes":           "",
    },
    {
        "state_id":        "pit_lane",
        "label":           "Voie des stands",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "PIT_MODE_DRIVING_INTO_PITS (1) / DRIVING_OUT (3) / DRIVING_OUT_OF_GARAGE (5)",
        "notes":           "",
    },
    {
        "state_id":        "pit_stop",
        "label":           "Stand / garage",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "PIT_MODE_IN_PIT (2) / IN_GARAGE (4)",
        "notes":           "",
    },
    {
        "state_id":        "on_track",
        "label":           "En piste (résiduel)",
        "politique":       "play",
        "game_state":      "GAME_INGAME_PLAYING (2)",
        "session_state":   "SESSION_INVALID (0) ou autre",
        "race_state":      "*",
        "pit_mode":        "PIT_MODE_NONE",
        "notes":           "Fallback.",
    },
    {
        "state_id":        "unknown",
        "label":           "Inconnu",
        "politique":       "stop",
        "game_state":      "Combinaison non prévue",
        "session_state":   "*",
        "race_state":      "*",
        "pit_mode":        "*",
        "notes":           "",
    },
]

POLITIQUE_MUSIQUE = {row["state_id"]: row["politique"] for row in TABLEAU_ETATS}

EVENEMENTS = [
    {
        "event_id":   "garage_return_pause_menu",
        "description": "paused → setup_menu/pit_lane/pit_stop",
        "effet":      "Verrouille la musique.",
    },
    {
        "event_id":   "garage_return_direct",
        "description": "setup_menu → pit_lane/pit_stop",
        "effet":      "Idem.",
    },
    {
        "event_id":   "race_start",
        "description": "green_flag pendant race",
        "effet":      "Autorise la musique.",
    },
]
